---
- hosts: localhost
  connection: local
  become: yes
  vars:
    target_user: "{{ target_user | default(lookup('env','USER')) }}"  # Fallback to the current user if target_user is not defined

  tasks:
    - name: Debug .xinitrc destination path
      debug:
        msg: "/home/{{ target_user }}/.xinitrc"

    - name: Install necessary packages
      pacman:
        name:
          - xorg
          - bspwm
          - sxhkd
          - terminator
          - xorg-xinit
          - xterm
          - feh
          - xorg-xauth
          - polybar
          - libinput-gestures
        state: present

    - name: Ensure home directory permissions are correct
      file:
        path: "/home/{{ target_user }}"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0755'

    - name: Ensure .Xauthority file exists
      file:
        path: "/home/{{ target_user }}/.Xauthority"
        state: touch
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0600'

    - name: Add user to video group
      user:
        name: "{{ target_user }}"
        groups: video
        append: yes

    - name: Add user to input group
      user:
        name: "{{ target_user }}"
        groups: input
        append: yes

    - name: Ensure .config directory exists for user
      file:
        path: "/home/{{ target_user }}/.config"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0755'

    - name: Create bspwm config directory
      file:
        path: "/home/{{ target_user }}/.config/bspwm"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0755'

    - name: Create sxhkd config directory
      file:
        path: "/home/{{ target_user }}/.config/sxhkd"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0755'

    - name: Ensure terminator config directory exists
      file:
        path: "/home/{{ target_user }}/.config/terminator"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0755'

    - name: Configure terminator transparency
      copy:
        dest: "/home/{{ target_user }}/.config/terminator/config"
        content: |
          [global_config]
          [keybindings]
          [profiles]
            [[default]]
            background_darkness = 0.85
            background_type = transparent
          [layouts]
          [plugins]
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'

    - name: Configure sxhkd hotkey to open a new Terminator window
      lineinfile:
        path: "/home/{{ target_user }}/.config/sxhkd/sxhkdrc"
        insertafter: EOF
        line: |
          # Open a new Terminator window
          super + shift + Return
              terminator
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'

    - name: Configure sxhkd hotkeys for workspace switching
      lineinfile:
        path: "/home/{{ target_user }}/.config/sxhkd/sxhkdrc"
        insertafter: EOF
        line: |
          # Workspace switching
          super + {1-9,0}
              bspc desktop -f '^{1-9,10}'
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'

    - name: Copy bspwm configuration
      copy:
        dest: "/home/{{ target_user }}/.config/bspwm/bspwmrc"
        content: |
          #!/bin/sh
          bspc monitor -d I II III IV V VI VII VIII IX X
          bspc config border_width 2
          bspc config window_gap 12
          bspc config split_ratio 0.52
          bspc config borderless_monocle true
          bspc config gapless_monocle true
          bspc rule -a Gimp desktop='^8' state=floating follow=on
          bspc rule -a Chromium desktop='^2'
          bspc rule -a mplayer2 state=floating
          bspc rule -a Kupfer.py focus=on
          bspc rule -a Screenkey manage=off
        mode: '0755'
        owner: "{{ target_user }}"
        group: "{{ target_user }}"

    - name: Configure libinput-gestures for three-finger swipe
      copy:
        dest: "/home/{{ target_user }}/.config/libinput-gestures.conf"
        content: |
          gesture swipe left 3 bspc desktop -f next
          gesture swipe right 3 bspc desktop -f prev
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'

    - name: Ensure libinput-gestures is started with the session
      lineinfile:
        path: "/home/{{ target_user }}/.xinitrc"
        insertbefore: "exec bspwm"
        line: "libinput-gestures-setup start &"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0755'

    - name: Ensure polybar config directory exists
      file:
        path: "/home/{{ target_user }}/.config/polybar"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0755'

    - name: Copy polybar configuration
      copy:
        dest: "/home/{{ target_user }}/.config/polybar/config"
        content: |
          [bar/example]
          width = 100%
          height = 24
          bottom = false
          modules-left = bspwm

          [module/bspwm]
          type = internal/bspwm
          label-focused = " " ; Replace with the icon for focused workspace
          label-occupied = " " ; Replace with the icon for occupied workspace
          label-empty = " "    ; Replace with the icon for empty workspace
          ; Add more label settings for different workspace states as needed

          ; ... rest of the polybar configuration ...
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'

    - name: Ensure polybar is started with the session
      lineinfile:
        path: "/home/{{ target_user }}/.xinitrc"
        insertbefore: "exec bspwm"
        line: "polybar example &"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0755'

    - name: Copy sxhkd configuration
      copy:
        dest: "/home/{{ target_user }}/.config/sxhkd/sxhkdrc"
        content: |
          # Logos key (Super_L is the left Win key)
          super + Return
              terminator
        mode: '0644'
        owner: "{{ target_user }}"
        group: "{{ target_user }}"

    - name: Copy .xinitrc file to user's home directory
      copy:
        dest: "/home/{{ target_user }}/.xinitrc"
        content: |
          #!/bin/sh
          # Set up an environment variable, if needed
          export SOME_VARIABLE="value"

          # Start some background applications
          xsetroot -solid grey &  # Set a solid grey background
          xrdb -merge ~/.Xresources &  # Load X resources (like terminal colors, fonts, etc.)

          # Set the background image using feh
          feh --bg-scale /home/{{ target_user }}/background.jpg &

          # Launch a terminal
          terminator &  # Replace 'terminator' with your preferred terminal emulator

          # Start the window manager or desktop environment
          exec bspwm
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0755'

    - name: Copy background image to user's home directory
      copy:
        src: /home/john/readme.md/background.jpg
        dest: "/home/{{ target_user }}/background.jpg"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'

    - name: Set the background image in bspwm config
      lineinfile:
        path: "/home/{{ target_user }}/.config/bspwm/bspwmrc"
        insertafter: EOF
        line: 'feh --bg-scale /home/{{ target_user }}/background.jpg'
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0755'

    # Add any additional tasks here

# End of playbook
