---
- hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Debug .xinitrc destination path
      debug:
        msg: "/home/{{ ansible_user_id }}/.xinitrc"

    - name: Gather facts
      setup:

    - name: Print all gathered facts
      debug:
        var: ansible_facts

    - name: Install necessary packages
      pacman:
        name:
          - xorg
          - bspwm
          - sxhkd
          - terminator
          - xorg-xinit
          - xterm
          - feh
          - xorg-xauth
        state: present

    - name: Ensure home directory permissions are correct
      file:
        path: "/home/{{ ansible_user_id }}"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0755'

    - name: Ensure .Xauthority file exists
      file:
        path: "/home/{{ ansible_user_id }}/.Xauthority"
        state: touch
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0600'

    - name: Add user to video group
      user:
        name: "{{ ansible_user_id }}"
        groups: video
        append: yes

    - name: Add user to input group
      user:
        name: "{{ ansible_user_id }}"
        groups: input
        append: yes

    - name: Ensure .config directory exists for user
      file:
        path: "/home/{{ ansible_user_id }}/.config"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0755'

    - name: Create bspwm config directory
      file:
        path: "/home/{{ ansible_user_id }}/.config/bspwm"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0755'

    - name: Create sxhkd config directory
      file:
        path: "/home/{{ ansible_user_id }}/.config/sxhkd"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0755'

    - name: Copy bspwm configuration
      copy:
        dest: "/home/{{ ansible_user_id }}/.config/bspwm/bspwmrc"
        content: |
          #!/bin/sh
          bspc monitor -d I II III IV V VI VII VIII IX X
          bspc config border_width 2
          bspc config window_gap 12
          bspc config split_ratio 0.52
          bspc config borderless_monocle true
          bspc config gapless_monocle true
          bspc rule -a Gimp desktop='^8' state=floating follow=on
          bspc rule -a Chromium desktop='^2'
          bspc rule -a mplayer2 state=floating
          bspc rule -a Kupfer.py focus=on
          bspc rule -a Screenkey manage=off
        mode: '0755'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"

    - name: Copy sxhkd configuration
      copy:
        dest: "/home/{{ ansible_user_id }}/.config/sxhkd/sxhkdrc"
        content: |
          # Logos key (Super_L is the left Win key)
          super + Return
              terminator
        mode: '0644'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"

    - name: Copy .xinitrc file to user's home directory
      copy:
        dest: "/home/{{ ansible_user_id }}/.xinitrc"
        content: |
          #!/bin/sh
          # Set up an environment variable, if needed
          export SOME_VARIABLE="value"

          # Start some background applications
          xsetroot -solid grey &  # Set a solid grey background
          xrdb -merge ~/.Xresources &  # Load X resources (like terminal colors, fonts, etc.)

          # Set the background image using feh
          feh --bg-scale /home/{{ ansible_user_id }}/background.jpg &

          # Launch a terminal
          terminator &  # Replace 'terminator' with your preferred terminal emulator

          # Start the window manager or desktop environment
          exec bspwm
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0755'

    - name: Copy background image to user's home directory
      copy:
        src: /home/john/readme.md/background.jpg  # Update this path to your local file
        dest: "/home/{{ ansible_user_id }}/background.jpg"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0644'

    - name: Ensure permissions are correct for the user's config directory
      file:
        path: "/home/{{ ansible_user_id }}/.config"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        recurse: yes

    - name: Set the background image in bspwm config
      lineinfile:
        path: "/home/{{ ansible_user_id }}/.config/bspwm/bspwmrc"
        insertafter: EOF
        line: 'feh --bg-scale /home/{{ ansible_user_id }}/background.jpg'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0755'
