---
- hosts: localhost
  connection: local
  become: yes
  vars:
    target_user: "{{ target_user }}"

  tasks:
    - name: Debug .xinitrc destination path
      debug:
        msg: "/home/{{ target_user }}/.xinitrc"

    - name: Install necessary packages
      pacman:
        name:
          - xorg
          - bspwm
          - sxhkd
          - terminator
          - xorg-xinit
          - xterm
          - feh
          - xorg-xauth
          - polybar
          - xf86-input-libinput
        state: present

    - name: Ensure home directory permissions are correct
      file:
        path: "/home/{{ target_user }}"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0755'

    - name: Ensure .Xauthority file exists
      file:
        path: "/home/{{ target_user }}/.Xauthority"
        state: touch
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0600'

    - name: Add user to video group
      user:
        name: "{{ target_user }}"
        groups: video
        append: yes

    - name: Add user to input group
      user:
        name: "{{ target_user }}"
        groups: input
        append: yes

    - name: Ensure .config directory exists for user
      file:
        path: "/home/{{ target_user }}/.config"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0755'

    - name: Create bspwm config directory
      file:
        path: "/home/{{ target_user }}/.config/bspwm"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0755'

    - name: Create sxhkd config directory
      file:
        path: "/home/{{ target_user }}/.config/sxhkd"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0755'

    - name: Ensure terminator config directory exists
      file:
        path: "/home/{{ target_user }}/.config/terminator"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0755'

    - name: Configure terminator transparency
      copy:
        dest: "/home/{{ target_user }}/.config/terminator/config"
        content: |
          [global_config]
          [keybindings]
          [profiles]
            [[default]]
            background_darkness = 0.85
            background_type = transparent
          [layouts]
          [plugins]
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'

    - name: Configure sxhkd hotkey to open a new Terminator window
      lineinfile:
        path: "/home/{{ target_user }}/.config/sxhkd/sxhkdrc"
        insertafter: EOF
        line: |
          # Open a new Terminator window
          super + shift + Return
              terminator
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'

    - name: Configure sxhkd hotkeys for workspace switching
      lineinfile:
        path: "/home/{{ target_user }}/.config/sxhkd/sxhkdrc"
        insertafter: EOF
        line: |
          # Workspace switching
          super + {1-9,0}
              bspc desktop -f '^{1-9,10}'
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'

    - name: Copy bspwm configuration
      copy:
        dest: "/home/{{ target_user }}/.config/bspwm/bspwmrc"
        content: |
          #!/bin/sh
          bspc monitor -d I II III IV V VI VII VIII IX X
          bspc config border_width 2
          bspc config window_gap 12
          bspc config split_ratio 0.52
          bspc config borderless_monocle true
          bspc config gapless_monocle true
          bspc rule -a Gimp desktop='^8' state=floating           follow=on
          bspc rule -a Chromium desktop='^2'
          bspc rule -a mplayer2 state=floating
          bspc rule -a Kupfer.py focus=on
          bspc rule -a Screenkey manage=off
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0755'

    - name: Ensure polybar config directory exists
      file:
        path: "/home/{{ target_user }}/.config/polybar"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0755'

    - name: Copy polybar configuration
      copy:
        dest: "/home/{{ target_user }}/.config/polybar/config"
        content: |
          [bar/example]
          width = 100%
          height = 24
          radius = 0
          fixed-center = false

          background = #222
          foreground = #fff

          line-size = 3
          line-color = #f00

          border-size = 0
          border-color = #00000000

          padding-left = 0
          padding-right = 2

          module-margin-left = 1
          module-margin-right = 2

          font-0 = "xos4 Terminus:size=10;1"
          font-1 = "siji:pixelsize=10;1"

          modules-left = bspwm
          modules-center = 
          modules-right = myclock

          [module/bspwm]
          type = internal/bspwm
          format = <label-monitors>
          label-monitors = <label-monitor> <label-desktops>
          label-monitor-foreground = #8FBCBB
          label-urgent-background = #BF616A
          label-urgent-foreground = #ECEFF4
          label-focused-background = #5E81AC
          label-focused-foreground = #ECEFF4
          label-occupied-foreground = #D08770
          label-empty-foreground = #656D78

          [module/myclock]
          type = internal/date
          interval = 1.0

          date = "%Y-%m-%d"
          time = "%H:%M:%S"

          format-prefix = " "
          format-prefix-foreground = #555
          format-foreground = #fff
          format-background = #222

          label = %date% %time%
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'

    - name: Copy .xinitrc file to user's home directory
      copy:
        dest: "/home/{{ target_user }}/.xinitrc"
        content: |
          #!/bin/sh
          # Set up an environment variable, if needed
          export SOME_VARIABLE="value"

          # Start some background applications
          xsetroot -solid grey &  # Set a solid grey background
          xrdb -merge ~/.Xresources &  # Load X resources (like terminal colors, fonts, etc.)

          # Set the background image using feh
          feh --bg-scale /home/{{ target_user }}/background.jpg &

          # Launch polybar
          polybar example &

          # Start Terminator
          terminator &

          # Start the window manager or desktop environment
          exec bspwm
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0755'

# End of playbook
